### ISSUE TITLE
Ledger Donjon code review

### ISSUE THREAD

**Issue by adrienlacombe-ledger** [bogdoslavik/harvest-ledger-plugin#7]
This pattern is a mess: https://github.com/LedgerHQ/app-plugin-harvest/blob/d8cf6dcd8c3f152fd130ed6a1284358409132744/src/handle_finalize.c#L30-L31

Can it be fixed properly, for example by including contracts-info-tests.txt when DEBUG=1, else contracts-info.txt? Currently both files are included, which is a non sense.

Moreover, prototype for `find_contract_info` should be:

`const contract_info_t *find_contract_info(const char *a);
`
Function should return `NULL` if contract is not found, instead of returning a struct by value and checking its fields.

Finally, the `_HARVEST` macro is bad. Developer introduced it because his plugin crashed, but this is not the proper way to do it:

```
// I have strange plugin crash with Signal 11 when tried read from predefined array of
// contract_info_t so used simple if-else-if chain
```

**Comment by bogdoslavik** [comment]
Ok with first 2 points.
Why macro is bad? It works well. And how it should be done 'properly'?

**Comment by bogdoslavik** [comment]
I fixed 1st 2 points, and tried again with #3:

1. when `DEBUG` is defind, `contracts-info-tests.txt` included 
2. `find_contract_info` now returns pointer insted of struct

With constant array of contract structs I still have no luck 
(see branch [`contracts-array`](https://github.com/bogdoslavik/harvest-ledger-plugin/tree/contracts-array) )
I replaced if-else chain to array.
It compiled well, but plugin crashes at the test time with `Signal 11` error.
I guess it can be some microcontroller memory restrictions I am not familiar with.
Please review and advice how it shold be done properly.

**Comment by adrienlacombe-ledger** [comment]
hi @bogdoslavik 

Plugins manipulates arrays of arrays. There is indeed a limitation because there is no proper loader in BOLOS: code is directly executed from flash memory, without any relocation.

Problem can be solved with the PIC() macro. See https://developers.ledger.com/docs/nano-app/position-independent-code/

**Comment by bogdoslavik** [comment]
Hi!
I tried many variants of PIC() usage with no luck. Same crash.
With one of variants (array of pointers to contract_info_t struct) I have compile time error 
`ld.lld: error: SBREL relocation to contracts without static base`

See contracts-array branch with one of not working solution.

Please help me to fix it or
lets use simple, effective and ready solution with if-else chain.

**Comment by adrienlacombe-ledger** [comment]
the issue is still related with `PIC()` the following should demonstrate what the issue is:

```
void print_contract_info(contract_info_t* ci) {
    PRINTF("underlying_decimals: %d\n", ci->underlying_decimals);
    PRINTF("vault_decimals: %d\n", ci->vault_decimals);
    char* address = (char*)PIC(ci->address);
    PRINTF("address: %.*H\n", PARAMETER_LENGTH, address);
}

contract_info_t *find_contract_info(const char *address) {
  [...]
  contract_info_t *ci = &contracts[i];
  print_contract_info(ci);
  [...]
}
```

The issue is that `address/underlying_ticker/vault_ticker` are pointers, so its needed to use the `PIC`

**Comment by adrienlacombe-ledger** [comment]
There are still a few issues note considering:

- add a break statement in https://github.com/bogdoslavik/harvest-ledger-plugin/blob/a06e9326cb7acfe82926439d7062fb9fcb70212c/src/handle_query_contract_ui.c#L40

- What is the need for https://github.com/bogdoslavik/harvest-ledger-plugin/blob/a06e9326cb7acfe82926439d7062fb9fcb70212c/src/harvest_plugin.h#L44-L45 does not seem necessary so remove it.

- main.c should add the following changes https://github.com/LedgerHQ/app-plugin-nft/commit/630fa1f473157e0c747953b05d6075ac7f9863da

- move these into a file called contract.c https://github.com/bogdoslavik/harvest-ledger-plugin/blob/a06e9326cb7acfe82926439d7062fb9fcb70212c/src/main.c#L28-L40

**Comment by bogdoslavik** [comment]
Memory issues fixed - thank you! 

1. As far, as I know `default` do not needs `break`. Added anyway :)
2. `offest` is used at handle_provide_parameter.c:5:46, `go_to_offset` at handle_provide_parameter.c:4:18 and 8:18. 
3. main.c merged
4. constants moved to contract.c

Ufff. Looks like all set :) 
Last time I wrote on C ~25 years ago, so sorry for dumb questions )))

**Comment by adrienlacombe-ledger** [comment]
thank you so much @bogdoslavik ! C still trending 25 years later ;)

**Comment by bogdoslavik** [comment]
1. I've added `DEFINES += DEBUG` to the Makefile, and uncommented #ifdef DEBUG
2. removed PIC()
3. changed to memcmp()
4. comments removed
5. unused vars removed

**Comment by adrienlacombe-ledger** [comment]
Donjon review done, thank you so much @bogdoslavik !

**Comment by bogdoslavik** [comment]
Great!
